# Source data (included preprocessed data from the dataset)
SOURCE_DATA_DIR = "source_data"
SOURCE_DATA_TYPES = {
    "Dst Port": "Int64",
    "Src Port": "Int64",
    "Protocol": "Int64",
    "Timestamp": "string",
    "Flow Duration": "Int64",
    "Tot Fwd Pkts": "Int64",
    "Tot Bwd Pkts": "Int64",
    "TotLen Fwd Pkts": "Int64",
    "TotLen Bwd Pkts": "Int64",
    "Fwd Pkt Len Max": "Int64",
    "Fwd Pkt Len Min": "Int64",
    "Fwd Pkt Len Mean": "float64",
    "Fwd Pkt Len Std": "float64",
    "Bwd Pkt Len Max": "Int64",
    "Bwd Pkt Len Min": "Int64",
    "Bwd Pkt Len Mean": "float64",
    "Bwd Pkt Len Std": "float64",
    "Flow Byts/s": "float64",
    "Flow Pkts/s": "float64",
    "Flow IAT Mean": "float64",
    "Flow IAT Std": "float64",
    "Flow IAT Max": "Int64",
    "Flow IAT Min": "Int64",
    "Fwd IAT Tot": "Int64",
    "Fwd IAT Mean": "float64",
    "Fwd IAT Std": "float64",
    "Fwd IAT Max": "Int64",
    "Fwd IAT Min": "Int64",
    "Bwd IAT Tot": "Int64",
    "Bwd IAT Mean": "float64",
    "Bwd IAT Std": "float64",
    "Bwd IAT Max": "Int64",
    "Bwd IAT Min": "Int64",
    "Fwd PSH Flags": "Int64",
    "Bwd PSH Flags": "Int64",
    "Fwd URG Flags": "Int64",
    "Bwd URG Flags": "Int64",
    "Fwd Header Len": "Int64",
    "Bwd Header Len": "Int64",
    "Fwd Pkts/s": "float64",
    "Bwd Pkts/s": "float64",
    "Pkt Len Min": "Int64",
    "Pkt Len Max": "Int64",
    "Pkt Len Mean": "float64",
    "Pkt Len Std": "float64",
    "Pkt Len Var": "float64",
    "FIN Flag Cnt": "Int64",
    "SYN Flag Cnt": "Int64",
    "RST Flag Cnt": "Int64",
    "PSH Flag Cnt": "Int64",
    "ACK Flag Cnt": "Int64",
    "URG Flag Cnt": "Int64",
    "CWE Flag Count": "Int64",
    "ECE Flag Cnt": "Int64",
    "Down/Up Ratio": "Int64",
    "Pkt Size Avg": "float64",
    "Fwd Seg Size Avg": "float64",
    "Bwd Seg Size Avg": "float64",
    "Fwd Byts/b Avg": "Int64",
    "Fwd Pkts/b Avg": "Int64",
    "Fwd Blk Rate Avg": "Int64",
    "Bwd Byts/b Avg": "Int64",
    "Bwd Pkts/b Avg": "Int64",
    "Bwd Blk Rate Avg": "Int64",
    "Subflow Fwd Pkts": "Int64",
    "Subflow Fwd Byts": "Int64",
    "Subflow Bwd Pkts": "Int64",
    "Subflow Bwd Byts": "Int64",
    "Init Fwd Win Byts": "Int64",
    "Init Bwd Win Byts": "Int64",
    "Fwd Act Data Pkts": "Int64",
    "Fwd Seg Size Min": "Int64",
    "Active Mean": "float64",
    "Active Std": "float64",
    "Active Max": "Int64",
    "Active Min": "Int64",
    "Idle Mean": "float64",
    "Idle Std": "float64",
    "Idle Max": "Int64",
    "Idle Min": "Int64",
    "Label": "string",
}
